spring.application.name=patientcare

spring.datasource.url=jdbc:postgresql://dragon-experience.de:40484/patientcare
spring.datasource.username=mse
spring.datasource.password=$+n@3YFcpMBH3P*,jKp@

# Set the ddl-auto behavior based on your requirements
spring.jpa.hibernate.ddl-auto=create-drop

# Specify PostgreSQL dialect for Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
